# Generated by Django 5.0.14 on 2026-08-19 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
        ('sharing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_urls', models.JSONField(help_text='Raw URLs as submitted, before resolution.')),
                ('source_type', models.CharField(choices=[('track', 'Track'), ('album', 'Album'), ('playlist', 'Playlist'), ('artist', 'Artist'), ('mixed', 'Mixed')], default='mixed', max_length=16)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolving', 'Resolving sources'), ('running', 'Running'), ('completed', 'Completed'), ('completed_with_errors', 'Completed with errors'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=24)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('completed_items', models.PositiveIntegerField(default=0)),
                ('failed_items', models.PositiveIntegerField(default=0)),
                ('cancelled_items', models.PositiveIntegerField(default=0)),
                ('error_summary', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='download_batches', to=settings.AUTH_USER_MODEL)),
                ('shared_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='download_batches', to='sharing.sharedimportlink')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DownloadItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=2048)),
                ('source_identifier', models.CharField(blank=True, db_index=True, help_text='e.g. the Spotify track ID, stable across re-imports.', max_length=64)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('artist', models.CharField(blank=True, max_length=255)),
                ('album', models.CharField(blank=True, max_length=255)),
                ('album_artist', models.CharField(blank=True, max_length=255)),
                ('playlist_name', models.CharField(blank=True, max_length=255)),
                ('playlist_position', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('downloading', 'Downloading'), ('processing', 'Processing'), ('completed', 'Completed'), ('duplicate_skipped', 'Skipped (duplicate)'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('duplicate_status', models.CharField(choices=[('unknown', 'Not checked'), ('new', 'New track'), ('exact_duplicate', 'Exact duplicate'), ('probable_duplicate', 'Probable duplicate')], default='unknown', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0, help_text='0-100')),
                ('current_stage', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='downloader.downloadbatch')),
                ('result_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='download_items', to='library.trackfile')),
            ],
            options={
                'ordering': ['playlist_position', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='downloadbatch',
            index=models.Index(fields=['created_by', '-created_at'], name='downloader__created_aaaf96_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadbatch',
            index=models.Index(fields=['status'], name='downloader__status_dd1a82_idx'),
        ),
        migrations.AddIndex(
            model_name='downloaditem',
            index=models.Index(fields=['batch', 'status'], name='downloader__batch_i_4eb338_idx'),
        ),
        migrations.AddIndex(
            model_name='downloaditem',
            index=models.Index(fields=['source_identifier'], name='downloader__source__9ea4ff_idx'),
        ),
        migrations.AddIndex(
            model_name='downloaditem',
            index=models.Index(fields=['status'], name='downloader__status_a51ff9_idx'),
        ),
    ]
