# Generated by Django 5.0.14 on 2026-08-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadbatch',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
