# Generated by Django 5.0.14 on 2026-08-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0002_downloadbatch_notified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloaditem',
            name='last_command',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='downloaditem',
            name='last_output',
            field=models.TextField(blank=True),
        ),
    ]
