# Generated by Django 5.0.14 on 2026-08-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0003_downloaditem_last_command_downloaditem_last_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloaditem',
            name='source_provider',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
