# Generated by Django 5.0.14 on 2026-08-19 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_language', models.CharField(blank=True, choices=[('en', 'English'), ('fi', 'Suomi')], help_text='Empty means use the site default.', max_length=10)),
                ('theme_preference', models.CharField(choices=[('auto', 'Automatic'), ('light', 'Light'), ('dark', 'Dark')], default='auto', max_length=10)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('notify_on_batch_complete', models.BooleanField(default=True)),
                ('notify_on_batch_failed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
