# Generated by Django 5.0.14 on 2026-08-19 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='spotDL Web UI', max_length=100)),
                ('maintenance_mode', models.BooleanField(default=False, help_text='When enabled, non-staff users see a maintenance page instead of the app.')),
                ('maintenance_message', models.TextField(blank=True)),
                ('default_download_format', models.CharField(default='mp3', max_length=10)),
                ('default_duplicate_policy', models.CharField(choices=[('skip', 'Skip duplicates'), ('keep_both', 'Keep both copies'), ('ask', 'Ask the user')], default='ask', max_length=20)),
                ('max_urls_per_batch', models.PositiveIntegerField(default=25)),
                ('navidrome_sync_enabled', models.BooleanField(default=False)),
                ('musicbrainz_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('login_failed', 'Login failed'), ('logout', 'Logout'), ('batch_created', 'Download batch created'), ('batch_cancelled', 'Download batch cancelled'), ('item_retried', 'Download item retried'), ('shared_link_created', 'Shared link created'), ('shared_link_disabled', 'Shared link disabled'), ('shared_link_used', 'Shared link used'), ('settings_changed', 'Settings changed'), ('admin_action', 'Administrative action')], max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('target_repr', models.CharField(blank=True, max_length=255)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='core_auditl_action_29a2bf_idx')],
            },
        ),
    ]
