# Generated by Django 5.0.14 on 2026-08-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='fallback_audio_providers',
            field=models.CharField(blank=True, default='soundcloud', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='primary_audio_provider',
            field=models.CharField(blank=True, choices=[('youtube', 'YouTube'), ('youtube-music', 'YouTube Music'), ('soundcloud', 'SoundCloud'), ('bandcamp', 'Bandcamp'), ('piped', 'Piped')], default='youtube', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='primary_provider_attempts',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
