# Generated by Django 5.0.14 on 2026-08-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_fallback_audio_providers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('login_failed', 'Login failed'), ('logout', 'Logout'), ('batch_created', 'Download batch created'), ('batch_cancelled', 'Download batch cancelled'), ('batch_retried', 'Download batch items retried'), ('item_retried', 'Download item retried'), ('shared_link_created', 'Shared link created'), ('shared_link_disabled', 'Shared link disabled'), ('shared_link_used', 'Shared link used'), ('settings_changed', 'Settings changed'), ('admin_action', 'Administrative action')], max_length=32),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='default_duplicate_policy',
            field=models.CharField(choices=[('skip', 'Skip duplicates'), ('keep_both', 'Keep both copies'), ('ask', 'Ask the user')], default='ask', help_text="What to do when a newly downloaded track's audio is byte-for-byte identical to one already in the library (CLAUDE.md #7). “Ask the user” currently behaves like “Keep both” — the item is flagged as a duplicate either way, just never silently discarded or overwritten (CLAUDE.md #21).", max_length=20),
        ),
    ]
