# Generated by Django 5.0.14 on 2026-08-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_auditlog_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('login_failed', 'Login failed'), ('logout', 'Logout'), ('batch_created', 'Download batch created'), ('batch_cancelled', 'Download batch cancelled'), ('batch_retried', 'Download batch items retried'), ('item_retried', 'Download item retried'), ('shared_link_created', 'Shared link created'), ('shared_link_disabled', 'Shared link disabled'), ('shared_link_used', 'Shared link used'), ('settings_changed', 'Settings changed'), ('duplicates_removed', 'Duplicate library files removed'), ('admin_action', 'Administrative action')], max_length=32),
        ),
    ]
