# Generated by Django 5.0.14 on 2026-08-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='auto_replace_probable_duplicates',
            field=models.BooleanField(default=True, help_text="When a newly downloaded track has the same artist/title as one already in the library but different audio (a “probable” duplicate — CLAUDE.md #7), automatically delete the older file and keep the new one when the new file is bigger, or was sourced from YouTube Music specifically. Plain YouTube search results are excluded from that second condition because they more often surface a live performance for the same title/artist — a genuinely different recording, not just a lower-quality copy of the studio one — so auto-replacing on that basis would risk losing it. Files this doesn't replace are kept as separate tracks, same as today."),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('login_failed', 'Login failed'), ('logout', 'Logout'), ('batch_created', 'Download batch created'), ('batch_cancelled', 'Download batch cancelled'), ('batch_retried', 'Download batch items retried'), ('item_retried', 'Download item retried'), ('shared_link_created', 'Shared link created'), ('shared_link_disabled', 'Shared link disabled'), ('shared_link_used', 'Shared link used'), ('settings_changed', 'Settings changed'), ('duplicates_removed', 'Duplicate library files removed'), ('library_scan_triggered', 'Library scan triggered'), ('admin_action', 'Administrative action')], max_length=32),
        ),
    ]
