# Generated by Django 5.0.14 on 2026-08-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesettings_auto_replace_probable_duplicates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='navidrome_sync_enabled',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='musicbrainz_sweep_batch_size',
            field=models.PositiveIntegerField(default=5, help_text='How many never-checked tracks the background MusicBrainz sweep looks up each time it runs (apps.musicbrainz.tasks.musicbrainz_sweep_task), instead of doing them all at once — MusicBrainz itself limits every deployment to about one request per second regardless, so a smaller number just means each sweep run finishes sooner and yields the shared rate limit back. The sweep only ever runs when no download batch is currently active, so it never competes with real downloads for a worker.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='musicbrainz_enabled',
            field=models.BooleanField(default=True, help_text='Look up MusicBrainz automatically right after each track finishes downloading, filling in its MusicBrainz ID and any missing album title from a high-confidence match, and in the slow background sweep below for tracks never checked. Never overwrites title/artist/album that are already populated — those can only be changed through the manual per-track review page (“Review metadata against MusicBrainz”), which is unaffected by this setting.'),
        ),
    ]
