# Generated by Django 5.0.14 on 2026-08-19 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicBrainzRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbid', models.CharField(help_text='MusicBrainz recording MBID', max_length=36, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('artist', models.CharField(blank=True, max_length=255)),
                ('artist_mbid', models.CharField(blank=True, max_length=36)),
                ('release', models.CharField(blank=True, max_length=255)),
                ('release_mbid', models.CharField(blank=True, max_length=36)),
                ('length_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('isrcs', models.JSONField(blank=True, default=list)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matched_track_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='musicbrainz_matches', to='library.trackfile')),
            ],
            options={
                'indexes': [models.Index(fields=['artist', 'title'], name='musicbrainz_artist_ee8414_idx')],
            },
        ),
    ]
